name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  ci:
    runs-on: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: go build staticmodtimefs.go
      - name: test
        run: go test
